# Generated by Django 2.1.1 on 2020-04-06 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('accountName', models.CharField(max_length=500)),
                ('PIN', models.CharField(max_length=4)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('dateTime', models.DateTimeField()),
                ('fromAccountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localDatabase.Account')),
                ('toAccountNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_requests_created', to='localDatabase.Account')),
            ],
        ),
    ]
