# Generated by Django 2.1.1 on 2020-04-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localDatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('creditCardNumber', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('PIN', models.CharField(max_length=4)),
                ('balance', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localDatabase.Account')),
            ],
        ),
    ]
